const StoryConstants = {
  STORY_RECEIVED: "STORY_RECEIVED",
  SEARCHES_RECEIVED: "SEARCHES_RECEIVED",
  STORY_REMOVED: "STORY_REMOVED",
  STORIES_RECEIVED: "STORIES_RECEIVED"
};

module.exports = StoryConstants;
